name: Delete old workflow runs
on:
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Delete workflow runs
        uses: JuvenileQ/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 7
